# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bayesinsight-optimizer',
                'doc_host': 'https://redam94.github.io',
                'git_url': 'https://github.com/redam94/bayesinsight-optimizer',
                'lib_path': 'bayesinsight_optimizer'},
  'syms': {'bayesinsight_optimizer.core': {'bayesinsight_optimizer.core.foo': ('core.html#foo', 'bayesinsight_optimizer/core.py')}}}
